# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 264)
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.book_line_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.book_line_inp.setGeometry(QtCore.QRect(290, 20, 291, 41))
        self.book_line_inp.setObjectName("book_line_inp")
        self.author_line_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.author_line_inp.setGeometry(QtCore.QRect(290, 70, 291, 41))
        self.author_line_inp.setObjectName("author_line_inp")
        self.search_settings_opt = QtWidgets.QComboBox(self.centralwidget)
        self.search_settings_opt.setGeometry(QtCore.QRect(20, 20, 261, 31))
        self.search_settings_opt.setStyleSheet("background-color: white; border-size: 1px;")
        self.search_settings_opt.setObjectName("search_settings_opt")
        self.search_settings_opt.addItem("")
        self.search_settings_opt.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 60, 261, 51))
        self.pushButton.setStyleSheet("background-color: white;")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 220, 561, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 150, 261, 31))
        self.comboBox.setStyleSheet("background-color: white; border-size: 1px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(290, 150, 251, 31))
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(550, 150, 31, 31))
        self.toolButton.setObjectName("toolButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.book_line_inp.setText(_translate("MainWindow", "Name of the book"))
        self.author_line_inp.setText(_translate("MainWindow", "Author of the book"))
        self.search_settings_opt.setItemText(0, _translate("MainWindow", "MANUAL"))
        self.search_settings_opt.setItemText(1, _translate("MainWindow", "AUTO"))
        self.pushButton.setText(_translate("MainWindow", "SEARCH"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SEARCH ENGINE"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ilibrary.com"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CHOOSE FOLDER TO SAVE</p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
